# Generated by rusjango add docker.
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:?Set ALLOWED_HOSTS before starting Compose}
      DATABASE_URL: ${DATABASE_URL:-}
      DATABASE_NAME: /data/db.sqlite3
    volumes:
      - rusjango-data:/data
    restart: unless-stopped

volumes:
  rusjango-data:
