"""Generated by rusjango add docker: configured ASGI entry point."""

import importlib

from rusjango import Rusjango
from rusjango.orm import configure_db
from rusjango.settings import load_settings

# Validate production configuration before importing application code.
_settings = load_settings("settings_docker.py")
_module, _attribute = {{ app_path }}.split(":", 1)
app = importlib.import_module(_module)
for _part in _attribute.split("."):
    app = getattr(app, _part)
if not isinstance(app, Rusjango):
    raise TypeError("Docker scaffolding requires a Rusjango application instance")
app.settings.clear()
app.settings.update(_settings)
app._asgi_app = None
configure_db(app.settings.get("DATABASE"))
app.load_installed_apps()
