# Generated by rusjango add docker.
FROM python:3.12-slim AS builder
WORKDIR /app
RUN python -m pip install --no-cache-dir uv
COPY . .
RUN uv sync --no-dev --no-editable

FROM python:3.12-slim AS runtime
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    RUSJANGO_SETTINGS=settings_docker.py
WORKDIR /app
RUN mkdir -p /data && chown 10001:10001 /data
COPY --from=builder --chown=10001:10001 /app /app
USER 10001:10001
EXPOSE 8000
CMD ["/app/.venv/bin/python", "-m", "uvicorn", "docker_app:app", "--host", "0.0.0.0", "--port", "8000"]
