"""Generated by rusjango add docker: explicit container configuration."""

import os

from rusjango.settings import load_settings

globals().update(load_settings({{ settings_path }}))

DEBUG = False
ALLOWED_HOSTS = [host.strip() for host in os.environ.get("ALLOWED_HOSTS", "").split(",") if host.strip()]
if not ALLOWED_HOSTS:
    raise RuntimeError("Set ALLOWED_HOSTS to a comma-separated list of allowed hostnames")

MIDDLEWARE = list(globals().get("MIDDLEWARE") or [])
if "rusjango.security.SecurityMiddleware" not in MIDDLEWARE:
    MIDDLEWARE.insert(0, "rusjango.security.SecurityMiddleware")

if globals().get("DATABASE"):
    DATABASE = dict(DATABASE)
    if os.environ.get("DATABASE_URL"):
        DATABASE.update(ENGINE="postgresql", URL=os.environ["DATABASE_URL"])
    elif str(DATABASE.get("ENGINE", "sqlite")).lower() == "sqlite":
        DATABASE["NAME"] = os.environ.get("DATABASE_NAME", "/data/db.sqlite3")
