"""Generated by rusjango add admin: explicit server-side model registration."""

from rusjango.admin import AdminSite


def create_site(app):
    site = AdminSite()
    # Register models here, or define register(site) in apps/<name>/admin.py.
    # Always choose explicit list_display/detail_fields.
    return site
