"""Generated by rusjango add tests: isolated ASGI test client."""

from dataclasses import dataclass
import importlib
import json as jsonlib
from pathlib import Path
import sys
import tomllib
from urllib.parse import unquote, urlsplit

import pytest_asyncio

from rusjango.orm import close_db, configure_db, init_db


@dataclass
class Response:
    status: int
    body: bytes
    headers: dict

    def json(self):
        return jsonlib.loads(self.body)


class TestClient:
    def __init__(self, app):
        self.app = app

    async def request(self, method, path, *, json=None):
        url = urlsplit(path)
        body = jsonlib.dumps(json).encode() if json is not None else b""
        messages = []
        received = False

        async def receive():
            nonlocal received
            if received:
                return {"type": "http.disconnect"}
            received = True
            return {"type": "http.request", "body": body, "more_body": False}

        async def send(message):
            messages.append(message)

        await self.app({
            "type": "http", "method": method.upper(), "path": unquote(url.path),
            "query_string": url.query.encode(), "headers": [(b"host", b"testserver")],
        }, receive, send)
        start = next(message for message in messages if message["type"] == "http.response.start")
        output = b"".join(message.get("body", b"") for message in messages if message["type"] == "http.response.body")
        return Response(start["status"], output, dict(start["headers"]))


@pytest_asyncio.fixture
async def client(monkeypatch):
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(root))
    monkeypatch.delenv("RUSJANGO_SETTINGS", raising=False)
    config = tomllib.loads((root / "pyproject.toml").read_text())["tool"]["rusjango"]
    module, attribute = config.get("app", "main:app").split(":", 1)
    app = importlib.import_module(module)
    for part in attribute.split("."):
        app = getattr(app, part)
    original = dict(app.settings)
    await close_db()
    try:
        app.settings["ALLOWED_HOSTS"] = ["testserver"]
        if original.get("DATABASE"):
            app.settings["DATABASE"] = {"ENGINE": "sqlite", "NAME": ":memory:"}
        configure_db(app.settings.get("DATABASE"))
        if app.settings.get("DATABASE"):
            await init_db()
        yield TestClient(app)
    finally:
        await close_db()
        app.settings.clear()
        app.settings.update(original)
        configure_db(None)
        sys.path.remove(str(root))
