"""Generated by rusjango add tests: adapt this endpoint to your application."""

import pytest


@pytest.mark.asyncio
async def test_home(client):
    response = await client.request("GET", "/")
    assert response.status == 200
    assert response.json() == {"message": "Hello Rusjango"}
